### PR TITLE
Fix compile errors

### PR DESCRIPTION
**Pull request by shawwn**
I did a fresh checkout of Signal just now. To my surprise, `npm run build` followed by `npm start` ended up showing two compile errors. When I opened it in Webstorm the IDE confirmed there were problems.

# Problem 1
image

```tsx
            <SelectBox
              items={categoryOptions}
              selectedValue={selectedCategoryId} // Error TS2322: Type 'number' is not assignable to type 'object'.
              onChange={(i) =>
                onChange({
                  programNumber: i * 8, // Choose the first instrument of the category
                  isRhythmTrack,
                })
              }
            />
```

Since `selectedCategoryId` is a number, then `SelectBox<T>` becomes `SelectBox<number>`. However, `SelectBox` currently requires `SelectBox<T extends object>`, causing an error because `number` doesn't extend `object`.

## Solution 1
Removed `extends object`

# Problem 2
image

```tsx
          dragSelectionGesture.onMouseDown(
            ev.nativeEvent,
            hitEventId,
            local,
            controlTransform,
            eventType, // Error TS2554: Expected 4 arguments, but got 5.
          )
```
The above `onMouseDown` method only takes 4 arguments:

```tsx
    onMouseDown<T extends ControllerEvent | PitchBendEvent>(
      e: MouseEvent,
      hitEventId: number,
      startPoint: Point,
      transform: ControlCoordTransform,
    ) {
```

## Solution 2
Removed `eventType,` from the list of args passed to `onMouseDown`

---

Looking at the git blame, those lines of code haven't changed in a very long time (since 2022), so I wonder why the compiler is suddenly detecting these errors. Were there recent changes to tsconfig? Or could it be because you made `eslint` changes? Either way, it's nice that these were caught. (Maybe they were warnings before?)

### CODE REVIEW

**Comment by shawwn** [comment]
It looks like Problem 1 was introduced in 0fa2c0de69228abbac1a5501ace3a69e638ef917:
image

As for Problem 2, I have no idea, because SelectBox has been defined as `SelectBox<T extends object>` for two years now, and the code that was causing the error has also been there for two years, so it seems like this error should have showed up a long time ago.

**Comment by ryohey** [comment]
The version of typescript used may be different. npm install and try npm run build again. VSCode is recommended as the development environment.

**Comment by shawwn** [comment]
Well, even if the version is different, this PR still fixes two legitimate problems. A different version of typescript missing those problems seems unrelated.

**Comment by ryohey** [comment]
okay I reproduced that errors. my dev environment was something wrong.
Thank you for fixing it!

**Review by ryohey — APPROVED** [review]
